- infrastructure/aat.tfvars
Reverts hmcts/ccfr-fees-register-admin-web#86
> Revert "sidm aat urls"

- infrastructure/saat.tfvars
> sidam url fix

- infrastructure/saat.tfvars
> test tidam

- charts/fees-register-frontend/Chart.yaml
- charts/fees-register-frontend/requirements.yaml
- charts/fees-register-frontend/values.template.yaml
Using latest version of fees chart and minor url fix etc
```
[ ] Yes
[x ] No
```
> fixed fees url

- infrastructure/aat.tfvars
> point to sidam

- Jenkinsfile_CNP
- charts/fees-register-frontend/Chart.yaml
- charts/fees-register-frontend/requirements.yaml
- charts/fees-register-frontend/values.aat.template.yaml
- charts/fees-register-frontend/values.template.yaml
- config/custom-environment-variables.json
- package.json
- server.js
- src/main/app.ts
- src/main/features/admin/routes-unsecured/health-info.ts
- src/main/routes/health.ts
- yarn.lock
Adding secrets as flex volumes
```
[ ] Yes
[x ] No
```
> helm - Adding secrets as flex volumes

- charts/fees-register-frontend/Chart.yaml
- charts/fees-register-frontend/requirements.yaml
- charts/fees-register-frontend/values.aat.template.yaml
- charts/fees-register-frontend/values.template.yaml
helm preview config
```
[ ] Yes
[x ] No
```
> helm preview config

- web.config
removed default headers
Server: Microsoft-IIS/x.x
X-Powered-By: ASP.NET
https://blogs.msdn.microsoft.com/jpsanders/2015/10/07/remove-server-and-x-powered-by-headers-from-your-azure-mobile-apps/
```
[ ] Yes
[ x] No
```
> added web.config and removed default headers

- infrastructure/aat.tfvars
- src/main/features/admin/routes-unsecured/health-info.ts
> Anil dhawale GitHub patch 1

- infrastructure/prod.tfvars
- src/main/features/admin/routes-unsecured/health-info.ts
update the IDAM URL for prod
```
[ ] Yes
[ X] No
```
> IDAM URL update for Prod

- src/main/features/admin/routes-unsecured/health-info.ts
> PAY-2232: added the space in comment

- infrastructure/main.tf
> FeeReg build issue fixes

- Dockerfile
- charts/fees-register-frontend/Chart.yaml
- charts/fees-register-frontend/requirements.yaml
- charts/fees-register-frontend/values.preview.template.yaml
- charts/fees-register-frontend/values.yaml
> Cleaning up docker

- Jenkinsfile_CNP
- charts/fees-register-frontend/Chart.yaml
- charts/fees-register-frontend/values.preview.template.yaml
- charts/fees-register-frontend/values.yaml
- infrastructure/main.tf
- package.json
- server.js
- src/main/app.ts
- src/main/modules/secrets/index.ts
- src/main/server.ts
- src/test/modules/secrets/secrets.ts
- yarn.lock
> Fix secrets and build failure

- infrastructure/main.tf
- package.json
> Moving to node 12

- Jenkinsfile_CNP
> Disable AAT ASE deployment

- src/main/features/admin/routes-unsecured/health-info.ts
> don't ignore certs

- src/main/app.ts
> Disable response caching

- charts/fees-register-frontend/Chart.yaml
- charts/fees-register-frontend/values.yaml
> Helm chart changes

- Jenkinsfile_nightly
- package.json
> Added nightly build

- acceptance-tests/codecept.conf.js
- acceptance-tests/test/end-to-end/pages/steps_file.js
- acceptance-tests/test/end-to-end/tests/CCFRAcceptanceTestConstants.js
- acceptance-tests/test/end-to-end/tests/CCFeesRegister_ApproverScreenValidation_test.js
- acceptance-tests/test/end-to-end/tests/CCFeesRegister_EditorScreenValidation_test.js
https://tools.hmcts.net/jira/browse/PAY-4310
Proxy removal
functional test changes to run even without clearing data
```
[ ] Yes
[x] No
```
> Feeadminnightlyfix

- acceptance-tests/test/end-to-end/pages/steps_file.js
- acceptance-tests/test/end-to-end/tests/CCFeesRegister_ApproverScreenValidation_test.js
- acceptance-tests/test/end-to-end/tests/CCFeesRegister_EditorScreenValidation_test.js
https://tools.hmcts.net/jira/browse/PAY-4405
Delete fees after creation in automation script
```
[ ] Yes
[x] No
```
> Added functionality to delete fee code after creation in automation

- src/test/features/admin/routes/v2/confirm-draft-approval.ts
- src/test/features/admin/routes/v2/fee-details.ts
> Demo final changes

- src/main/features/admin/paths.ts
- src/main/features/admin/routes-unsecured/view-fee-version-history.ts
- src/main/features/admin/routes-unsecured/view-fees.ts
- src/main/features/admin/v2/views/external-fees.njk
- src/main/features/admin/v2/views/fee.njk
- src/main/public/stylesheets/feesCustom.css
- src/main/views/govukTemplate1.njk
- src/main/views/includes/propositional_navigation1.njk
- src/main/views/layout1.njk
> 5122 changes

- Jenkinsfile_nightly
- audit.json
> Suppress security on audit file

- package.json
- yarn.lock
> cve issue fixes

- charts/fees-register-frontend/Chart.yaml
> Chart version upgrade changes

- acceptance-tests/test/end-to-end/helpers/freg_helper.js
- acceptance-tests/test/end-to-end/pages/steps_file.js
- acceptance-tests/test/end-to-end/tests/CCFeesRegister_EditorScreenValidation_test.js
- src/main/app/fees/v2/feesClient.ts
- src/main/features/admin/v2/routes/create-edit-fee.ts
https://tools.hmcts.net/jira/browse/PAY-5754
```
[ ] Yes
[X] No
```
> refactor and fix functional tests

- acceptance-tests/test/end-to-end/tests/CCFeesRegister_ApproverScreenValidation_test.js
- acceptance-tests/test/end-to-end/tests/CCFeesRegister_EditorScreenValidation_test.js
> Pay 5898 fix functional tests

- infrastructure/main.tf
> update azurerem version

- scripts/pa11y.js
6216
Made an amendment to create initial PR
```
[ ] Yes
[ x] No
```
> initial setup

- charts/fees-register-frontend/Chart.yaml
- charts/fees-register-frontend/values.yaml
PAY_6611
Version update
- [ x ] Does this PR introduce a breaking change
> version update

- package.json
- src/test/features/admin/routes/v2/csv-upload.ts
- src/test/http-mocks/v2/fees.ts
- yarn.lock
https://tools.hmcts.net/jira/browse/PAY-6833
Update to nock to fix an issue with lodash having a vulnerability.
> PAY-6833: Dependency vulnerability with lodash

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/PAY-6974
upgrade express to address vulnerability "Open Redirect in malformed URLs"
> PAY-6974 use express 4.19.2

- package.json
- yarn.lock
PAY-6999: Pipeline fixes - week beginning 8th April 2024
[PAY-6999] (https://tools.hmcts.net/jira/browse/PAY-6999).
> [PAY-6999: Pipeline fixes - week beginning 8th April 2024

- .gitignore
- acceptance-tests/test/end-to-end/helpers/idam_helper.js
- package.json
- src/main/app.ts
- src/main/app/idam/security.js
- src/main/server.ts
- yarn.lock
https://tools.hmcts.net/jira/browse/PAY-7015
Fix login for ITHC.
> Pay 7015 fix ithc login

- .gitignore
- package.json
- src/main/app.ts
- src/main/app/idam/security.js
- src/main/server.ts
- yarn.lock
https://tools.hmcts.net/jira/browse/PAY-6747
Fixes IdAM logon locally.
- [] README and other documentation has been updated / added (if needed)
- [] tests have been updated / new tests has been added (if needed)
- [] Does this PR introduce a breaking change
> PAY-6747: IdAM Fix

- sonar-project.properties
https://tools.hmcts.net/jira/browse/PAY-6747
Fix build issue and some CVEs.
> PAY-6747: Fix Sonarqube issue.

- Jenkinsfile_nightly
[PAY-7194: Pipeline fixes - week beginning 17 Jun 2024
[PAY-7194] (https://tools.hmcts.net/jira/browse/PAY-7194).
> [PAY-7194: Pipeline fixes - week beginning 17 Jun 2024

- Jenkinsfile_nightly
- src/main/app/idam/security.js
- src/main/routes/logout.ts
PAY-7199: Redirect issue in ccfr-fees-register-admin-web
[PAY-7199] (https://tools.hmcts.net/jira/browse/PAY-7199).
> Pay 7199 nighty dev fix

- Jenkinsfile_nightly
- src/main/app/idam/security.js
- src/main/routes/logout.ts
PAY-7199: Redirect issue in ccfr-fees-register-admin-web
[PAY-7199] (https://tools.hmcts.net/jira/browse/PAY-7199).
> PAY-7199: Redirect issue in ccfr-fees-register-admin-web

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/PAY-7279
azure identity upgrade
> PAY-7231 upgrade @azure/identity pipeline fix

- src/main/public/js/exportexcel.js
- src/main/server.ts
See [PAY-7120](https://tools.hmcts.net/jira/browse/PAY-7120)
Rework done for the VUL-6113
Create a fee with teh desctiption of -cmd.  Test removed the -cmd
> PAY-7120 addressed VUL-6113 rework

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/PAY-7302
Update to version micromatch.
Pipeline green.
> PAY-7302: Update to fix CVE issue

- README.md
https://tools.hmcts.net/jira/browse/PAY-7520
See https://tools.hmcts.net/jira/browse/PAY-7520
To trigger a build
N/A
> PAY-7520 to trigger a build

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/CME-323
- [ x] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
> CME-323: Update azurerm

- acceptance-tests/test/end-to-end/tests/CCFeesRegister_EditorScreenValidation_test.js
PAY-7517: Resolve problem  for users deleted by IDAM team
[PAY-7517] (https://tools.hmcts.net/jira/browse/PAY-7517).
>  PAY-7517: Resolve problem  for users deleted by IDAM team

- package.json
- yarn.lock
See [PAY-7671](https://tools.hmcts.net/jira/browse/PAY-7671)
PAY-7671 addressed CVE-2025-27789
Ran application locally
> PAY-7671 addressed CVE-2025-27789

- charts/fees-register-frontend/Chart.yaml
- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/CME-414
- [ x] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
- [ x] Does this PR introduce a breaking change
> CME-414: Update pa11y, nodejs and OCI endpoint 

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/CME-485
Upgraded Axios package to fix security vulnerabilities
> Upgraded Axios package due to security vulnerabilities

- package.json
- yarn.lock
PAY-7859: Pipeline fixes - week beginning 9 of June 2025
[PAY-7859] (https://tools.hmcts.net/jira/browse/PAY-7859).
>  PAY-7859: Pipeline fixes - week beginning 9 of June 2025
